### ISSUE TITLE
Issue 1 Menno

### ISSUE THREAD

**Issue by Mennovlaming** [MartijnvdLans/real-time-web-2223#1]
- Ik heb 2 tabs open, de personen online is nog niet accuraat.
- Send button nog styling aan toevoegen
- Bij het eerste scherm selecteer naam, dacht ik dat ik een naam moest selecteren, misschien kan je het anders verwoorden, bijvoorbeeld wat is je naam.

**Comment by MartijnvdLans** [comment]
Opgelost:
- hosten via OnRender, Adaptable werkt nog niet heel lekker
- Styling moet nog helemaal om (niet tevreden)
- Anders verwoord
- 
Thanks!
