### ISSUE TITLE
Node modules

### ISSUE THREAD

**Issue by EvaZ7** [MartijnvdLans/real-time-web-2223#3]
Je hebt per ongeluk je node modules meegestuurd naar je github

**Comment by PipHarsveld** [comment]
Je hebt wel een .gitignore file maar deze is leeg, voeg in dat bestand deze regels toe en verwijder de map van github.

```
.DS_Store
.vscode
node_modules
```

**Comment by MartijnvdLans** [comment]
Thanks! Opgelost!
