### ISSUE TITLE
Bug met mensen online

### ISSUE THREAD

**Issue by PipHarsveld** [MartijnvdLans/real-time-web-2223#5]
De functie om te zien welke mensen online zijn lijkt in het begin te werken, maar na tijdje (x aantal seconden?) verdwijnen de personen uit de lijst en zijn er dus geen mensen meer online terwijl het tabblad nog wel open staat. 

Ik weet niet hoe je deze functie nu heb geschreven, maar je zou deze code moeten triggeren op het moment dat een user disconnect.

![image](https://user-images.githubusercontent.com/54938035/233593954-319e64c0-3e8e-4f96-8d20-21ef0268257e.png)

**Comment by MartijnvdLans** [comment]
Opgelost:
hosten via OnRender, Adaptable werkt nog niet heel lekker
